on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Dependency Modules
        shell: pwsh
        run: Install-Module ModuleBuilder -Force

      - name: Build Module
        shell: pwsh
        run: ./build.ps1
      
      - name: Upload Built Module
        uses: actions/upload-artifact@v4
        with:
          path: ./Output
          name: PSSessionize

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test Module
        uses: ./.github/actions/test-module
  
  release:
    needs: test
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v5

      - name: Create a Release
        uses: softprops/action-gh-release@v2