on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Dependency Modules
        shell: pwsh
        run: Install-Module Pester -Force; Install-Module ModuleBuilder -Force

      - name: Build Module
        shell: pwsh
        run: ./build.ps1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Module
        uses: ./.github/actions/test-module