on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Dependency Modules
        shell: pwsh
        run: Install-Module ModuleBuilder -Force

      - name: Build Module
        shell: pwsh
        run: ./build.ps1
      
      - name: Upload Built Module
        uses: actions/upload-artifact@v4
        with:
          path: ./Output

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test Module
        uses: ./.github/actions/test-module
  
  release:
    needs: test
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.ref, '/tags/') }}
    steps:
      - uses: actions/checkout@v5

      - name: Download Built Module
        uses: actions/download-artifact@v4

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: My Module Release
          tag: ${{ github.ref_name }}
          workdir: Output