on:
  push: 
    branches: [main]
    tags: [v*]

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Build Module
        shell: pwsh
        run: Install-Module ModuleBuilder -Force

      - name: Build Module
        shell: pwsh
        run: ./build.ps1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./Output
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5

      - name: Test Module
        uses: ./.github/actions/test-module

  release:
    permissions:
      contents: write
      
    needs: test
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - name: Release Module
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
